name: yShopPlugin
version: '1.2'
api-version: 1.13
main: pl.yshop.plugin.bukkit.BukkitPlugin
description: Plugin for communication with yshop.pl api
website: https://yshop.pl
author: 'yShop Contributors'
